//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.10 at 11:18:36 PM IST 
//


package com.example.webservices.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElectronicProductsRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElectronicProductsRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getElectronicProducts" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElectronicProductsRequest", propOrder = {
    "getElectronicProducts"
})
@XmlRootElement(name="ElectronicProductsRequest")
public class ElectronicProductsRequest {

    protected boolean getElectronicProducts;

    /**
     * Gets the value of the getElectronicProducts property.
     * 
     */
    public boolean isGetElectronicProducts() {
        return getElectronicProducts;
    }

    /**
     * Sets the value of the getElectronicProducts property.
     * 
     */
    public void setGetElectronicProducts(boolean value) {
        this.getElectronicProducts = value;
    }

}
