//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.10 at 11:18:36 PM IST 
//


package com.example.webservices.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElectronicProductsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElectronicProductsResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mobile" type="{http://www.example.org/products}mobile"/>
 *         &lt;element name="television" type="{http://www.example.org/products}television"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElectronicProductsResponse", propOrder = {
    "mobile",
    "television"
})
@XmlRootElement(name="ElectronicProductsResponse")
public class ElectronicProductsResponse {

    @XmlElement(required = true)
    protected Mobile mobile;
    @XmlElement(required = true)
    protected Television television;

    /**
     * Gets the value of the mobile property.
     * 
     * @return
     *     possible object is
     *     {@link Mobile }
     *     
     */
    public Mobile getMobile() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mobile }
     *     
     */
    public void setMobile(Mobile value) {
        this.mobile = value;
    }

    /**
     * Gets the value of the television property.
     * 
     * @return
     *     possible object is
     *     {@link Television }
     *     
     */
    public Television getTelevision() {
        return television;
    }

    /**
     * Sets the value of the television property.
     * 
     * @param value
     *     allowed object is
     *     {@link Television }
     *     
     */
    public void setTelevision(Television value) {
        this.television = value;
    }

}
