//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.10 at 11:18:36 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.webservices.pojo;
